zodiac/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('gateway.urls')),
    path('admin/', admin.site.urls),
]

gateway/models.py
import json
from http.client import responses

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django_celery_results.models import TaskResult


class User(AbstractUser):
    pass


class Source(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    apikey = models.CharField(max_length=32)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('sources-detail', args=[self.pk])

    def get_update_url(self):
        return reverse('sources-update', args=[self.pk])

    @classmethod
    def get_list_url(self):
        return reverse('sources-list')


class Application(models.Model):
    name = models.CharField(max_length=64, unique=True)
    is_active = models.BooleanField(default=True)
    app_host = models.CharField(max_length=40)
    app_port = models.PositiveSmallIntegerField(null=True, blank=True)
    health_check_path = models.CharField(max_length=255, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} ({}:{})".format(self.name, self.app_host, self.app_port)

    def get_update_url(self):
        return reverse('applications-update', args=[self.pk])

    def get_absolute_url(self):
        return reverse('applications-detail', args=[self.pk])

    @classmethod
    def get_list_url(self):
        return reverse('applications-list')


class ServiceRegistry(models.Model):
    REMOTE_AUTH = 0
    KEY_AUTH = 2
    PLUGIN_CHOICE_LIST = (
        (REMOTE_AUTH, _('Remote auth')),
        (KEY_AUTH, _('Key auth')),
    )
    HTTP_REQUESTS_METHODS = (
        ('GET', 'GET'),
        ('POST', 'POST'),
    )
    name = models.CharField(max_length=128)
    application = models.ForeignKey(
        Application,
        on_delete=models.CASCADE,
    )
    description = models.TextField()
    external_uri = models.CharField(max_length=40, blank=True, null=True)
    service_route = models.CharField(max_length=40)
    plugin = models.IntegerField(choices=PLUGIN_CHOICE_LIST, default=0)
    sources = models.ManyToManyField(Source, blank=True)
    is_active = models.BooleanField(default=True)
    is_private = models.BooleanField(default=False)
    has_active_task = models.BooleanField(default=False)
    has_external_trigger = models.BooleanField(default=False)
    method = models.CharField(max_length=10, choices=HTTP_REQUESTS_METHODS)
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["application__name", "name"]

    # TODO: validation
    # - unique together: application__app_host, application__app_port, service_route
    # - external_uri required when has_external_trigger == True

    def __str__(self):
        return self.name

    @property
    def full_name(self):
        return "{}: {}".format(self.application.name, self.name)

    def get_update_url(self):
        return reverse('services-update', args=[self.pk])

    def get_absolute_url(self):
        return reverse('services-detail', args=[self.pk])

    @classmethod
    def get_list_url(self):
        return reverse('services-list')

    def get_clear_errors_url(self):
        return reverse('services-clear-errors', args=[self.pk])

    def get_trigger_url(self):
        return reverse('services-trigger', args=[self.pk])

    def service_active(self):
        return True if (self.is_active and self.application.is_active) else False


class RequestLog(models.Model):
    service = models.ForeignKey(
        ServiceRegistry,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='requestlog'
    )
    status_code = models.CharField(max_length=4, blank=True, null=True)
    request_url = models.URLField(blank=True, null=True)
    async_result_id = models.CharField(max_length=36, blank=True, null=True)
    created_time = models.DateTimeField(auto_now_add=True)
    task_result = models.ForeignKey(TaskResult, on_delete=models.CASCADE, blank=True, null=True, related_name='request_log')
    task_result_status = models.CharField(max_length=100, choices=(('success', 'Success'), ('error', 'Error'), ('idle', 'Idle')), blank=True, null=True)

    @property
    def error_messages(self):
        # todo fix it here.
        errors = []
        if self.task_result:
            for e in json.loads(self.task_result.result).get('exc_message', []):
                try:
                    emess = e.get('detail')
                except BaseException:
                    try:
                        code = int(e[e.find("[") + 1:e.find("]")])
                        emess = f"{e}: {responses[code]}".replace("<", "").replace(">", "")
                    except BaseException:
                        emess = e
                errors.append(emess)
        return errors

zodiac/management/templates/management/results_detail.html
{% extends "management/base.html" %}

{% block h1_title %}
  Result Detail
  <small>{{object.date_done}}</small>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-body">
        <label>Identifier</label>
        <p>{{object.task_id}}</p>
        <label>Status</label>
        <p>{{object.status}}</p>
        {% if object.task_args %}
          <label>Arguments</label>
          {{object.task_args}}
        {% endif %}
        {% if object.task_kwargs %}
          <label>Keyword Arguments</label>
          {{object.task_kwargs}}
        {% endif %}
        <label>Result</label>
        <p><pre><code>{{ object.result }}</code></pre></p>
        {% if object.traceback %}
          <label>Traceback</label>
          <p><pre><code>{{object.traceback}}</code></pre></p>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript">
  var trigger_url = '{{ object.get_trigger_url }}'
  $(document).ready(function(){
    $('#trigger-service-btn').click(function(){
      $.get(trigger_url,{}, function(resp){
        if(resp.SUCCESS == 1){
          alert('it worked, request queued')
	      retrieve_objects_async_results();
        }
      });
    })

    retrieve_objects_async_results();
  });


  var retrieve_objects_async_results = function(){
    // ajax request to retrieve queue by objects
    $.get('{{ object.get_async_results_data_url }}', {}, function(resp){
      console.log(resp);
    });
  }
</script>
{% endblock %}

zodiac/management/templates/management/results_list.html
{% extends "management/base.html" %}

{% block h1_title %}
  Results
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-body no-padding">
        {% if object_list %}
          {% include 'management/results_list_table.html' %}
        {% else %}
          <li>No results yet.</li>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

zodiac/management/templates/management/services_delete.html
{% extends "management/base.html" %}

{% block h1_title %}
  Delete Service
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <form method="post">
      <div class="box box-primary">
        <div class="box-body">
          {% csrf_token %}
          <p>Are you sure you want to delete <strong>{{ object }}</strong>?</p>
          {{form.as_p}}
        </div>
        <div class="box-footer">
          <input class="btn btn-primary" type="submit" value="Confirm" />
          <a class="btn btn-danger" href="{{object.get_absolute_url}}">Cancel</a>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

zodiac/management/templates/management/services_detail.html
{% extends "management/base.html" %}

{% block h1_title %}
  {{object.name}} Service Detail
  <small>{% include 'management/active_label.html' with status=object.is_active %}</small>
  {% if object.is_private %}<small><span class="label label-warning">Private</span></small>{% endif %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-body">
        <label>Application></label>
        <p><a href="{{object.application.get_absolute_url}}">{{object.application}}</a></p>
        <label>Description</label>
        <p>{{object.description}}</p>
        <label>External uri</label>
        <p><code>{{object.method}} {{object.external_uri}}</code></p>
        <label>Service route</label>
        <p><code>{{object.method}} {{object.service_route}}</code></p>
        <label>Plugin</label>
        <p>{{object.get_plugin_display}}</p>
        {% if object.consumers.all %}
        <label>Consumers</label>
        <ul class="list-unstyled">
        {% for consumer in object.consumers.all %}
          <li>{{consumer}}</li>
        {% endfor %}
        </ul>
        {% endif %}
      </div>
      <div class="box-footer">
        <a href="{{ object.get_update_url }}" class="btn btn-primary">Edit Service</a>
        <a href="#" id="trigger-service-btn" class="btn btn-success pull-right">Manually Trigger</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript">
  var trigger_url = '{{ object.get_trigger_url }}'
  $(document).ready(function(){
    $('#trigger-service-btn').click(function(){
      $.get(trigger_url,{}, function(resp){
        if(resp.SUCCESS == 1){
          alert('it worked, request queued')
	      retrieve_objects_async_results();
        }
      });
    })

    retrieve_objects_async_results();
  });


  var retrieve_objects_async_results = function(){
    // ajax request to retrieve queue by objects
    $.get('{{ object.get_async_results_data_url }}', {}, function(resp){
      console.log(resp);
    });
  }
</script>
{% endblock %}

zodiac/management/templates/management/services_list.html
{% extends "management/base.html" %}

{% block h1_title %}
  Services
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-body no-padding">
        {% if object_list %}
          {% include 'management/services_list_table.html' %}
        {% else %}
          <li>No services yet.</li>
        {% endif %}
      </div>
      <div class="box-footer">
        <a class="btn btn-primary" href="{% url 'services-add' %}">Add Service</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

zodiac/management/templates/management/services_list_table.html
<table class="table table-striped">
  <tbody>
    {% for service in object_list %}
      <tr>
        <td><a href="{{ service.get_absolute_url }}">{{ service.name }}</a></td>
        <td>{% include 'management/active_label.html' with status=service.service_active %}</td>
        <td>{{service.description}}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

zodiac/management/templates/management/services_update.html
{% extends "management/base.html" %}
{% load crispy_forms_tags %}

{% block h1_title %}
  Edit System
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <form method="post">
      <div class="box box-primary">
        <div class="box-body">
          {% csrf_token %}
          {{form|crispy}}
        </div>
        <div class="box-footer">
          <input class="btn btn-primary" type="submit" value="Update" />
          <a href="{{object.get_absolute_url}}" class="btn btn-danger">Cancel</a>
          <a href="{% url 'services-delete' pk=object.pk %}" class="btn btn-warning pull-right">Delete</a>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

zodiac/management/templates/management/systems_delete.html
{% extends "management/base.html" %}

{% block h1_title %}
  Delete System
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <form method="post">
      <div class="box box-primary">
        <div class="box-body">
          {% csrf_token %}
          <p>Are you sure you want to delete <strong>{{ object }}</strong>?</p>
          {{form.as_p}}
        </div>
        <div class="box-footer">
          <input class="btn btn-primary" type="submit" value="Confirm" />
          <a class="btn btn-danger" href="{{object.get_absolute_url}}">Cancel</a>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

zodiac/management/templates/management/systems_detail.html
{% extends "management/base.html" %}

{% block h1_title %}
  {{object.name}} System Detail
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-body">
        <label>App host</label>
        <p>{{object.app_host}}</p>

        {% if object.app_port %}
        <label>App port</label>
        <p>{{object.app_port}}</p>
        {% endif %}

        {% if object.serviceregistry_set.all %}
        <label>Services</label>
        <ul class="list-unstyled">
        {% for service in object.serviceregistry_set.all %}
          <li><a href="{{service.get_absolute_url}}">{{service}}</a></li>
        {% endfor %}
        </ul>
        {% endif %}

      </div>
      <div class="box-footer">
        <a href="{{ object.get_update_url }}" class="btn btn-primary">Edit System</a>
      </div>
    </div>
  </div>
{% endblock %}

zodiac/management/templates/management/systems_list_table.html
<table class="table table-striped">
  <tbody>
    {% for system in object_list %}
      <tr>
        <td><a href="{{ system.get_absolute_url }}">{{ system.name }}</a></td>
        <td>{% include 'management/active_label.html' with status=system.is_active %}</td>
        <td>{{system.app_host}}:{{system.app_port}}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

zodiac/management/templates/management/systems_update.html
{% extends "management/base.html" %}
{% load crispy_forms_tags %}

{% block h1_title %}
  Edit System
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <form method="post">
      <div class="box box-primary">
        <div class="box-body">
          {% csrf_token %}
          {{form|crispy}}
        </div>
        <div class="box-footer">
          <input class="btn btn-primary" type="submit" value="Update" />
          <a href="{{object.get_absolute_url}}" class="btn btn-danger">Cancel</a>
          <a href="{% url 'systems-delete' pk=object.pk %}" class="btn btn-warning pull-right">Delete</a>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}